### ISSUE TITLE
Any plans to publish to NPM?

### ISSUE THREAD

**Issue by Traviskn** [robinpowered/react-native-fetch-polyfill#4]
I found this package after encountering the timeout issues described in https://github.com/facebook/react-native/issues/2556.  I'm testing out this polyfill in a project and was curious if there are any plans to publish it to NPM?

Thanks for the great work on this!

**Comment by vijayst** [comment]
I published it to npm. Please let me know if I should add contributors to npm registry. Thanks.

**Comment by atticoos** [comment]
Hey @vijayst - thanks for getting this up on the registry! Apologies for the delay @Traviskn.

Could you add [atticoos](https://www.npmjs.com/~atticoos) as the owner?

```
npm owner add atticoos react-native-fetch-polyfill
```

Thank you

**Comment by vijayst** [comment]
Added atticoos.

**Comment by atticoos** [comment]
Thanks!

Closing this out now that we're up on the registry 👍
